# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-04 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0003_auto_20191104_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 14, 25, 6222)),
        ),
    ]
