# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0004_auto_20191104_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='split_number',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='splitztopic', max_length=240),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 7, 50, 36, 774649)),
        ),
    ]
