# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-07 06:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0005_auto_20191106_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitamountledger',
            name='topic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sa_ledger_topic', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 6, 35, 43, 274202)),
        ),
    ]
