# Generated by Django 2.1.8 on 2019-12-26 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0008_auto_20191213_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 7, 1, 40, 514964)),
        ),
        migrations.AlterField(
            model_name='splitamountledger',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_ledger_topic', to='coresetup.Topic'),
        ),
    ]
