# Generated by Django 2.1.8 on 2020-01-03 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0009_auto_20191226_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 3, 28, 35, 564805)),
        ),
    ]
