# Generated by Django 2.1.8 on 2020-01-04 04:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0010_auto_20200103_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 4, 48, 45, 207282)),
        ),
        migrations.AddField(
            model_name='topicmembers',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TpoicOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='members_list',
            field=models.ManyToManyField(to='coresetup.TopicMembers'),
        ),
    ]
