# Generated by Django 2.1.8 on 2020-01-04 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0011_auto_20200104_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 13, 48, 58, 185473)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='members_list',
            field=models.ManyToManyField(blank=True, to='coresetup.TopicMembers'),
        ),
    ]
