# Generated by Django 2.1.8 on 2020-01-04 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0012_auto_20200104_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 13, 49, 45, 902165)),
        ),
        migrations.AlterField(
            model_name='topicmembers',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TopicOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
