# Generated by Django 2.1.8 on 2020-01-08 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0013_auto_20200104_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmembers',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='topicmembers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='members_list',
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 15, 8, 54, 348045)),
        ),
        migrations.DeleteModel(
            name='TopicMembers',
        ),
    ]
