# Generated by Django 2.1.8 on 2020-01-29 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0014_auto_20200108_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 7, 55, 19, 777950)),
        ),
    ]
