# Generated by Django 2.1.8 on 2020-01-29 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0016_auto_20200129_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 7, 55, 56, 723633)),
        ),
    ]
