# Generated by Django 2.1.8 on 2020-02-02 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0018_auto_20200129_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.CharField(default='Sharing with Friends and Families', max_length=240),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 15, 36, 43, 307065)),
        ),
    ]
