# Generated by Django 2.1.8 on 2020-02-03 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0019_auto_20200202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 9, 38, 0, 394094)),
        ),
    ]
