# Generated by Django 2.1.8 on 2020-02-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0020_auto_20200203_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 8, 51, 1, 876671)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
