# Generated by Django 2.1.8 on 2020-03-11 10:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0021_auto_20200204_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=80, unique=True)),
                ('entity', models.CharField(blank=True, default='', max_length=80)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('amount_paid', models.IntegerField(blank=True, default=0)),
                ('amount_due', models.IntegerField(blank=True, default=0)),
                ('currency', models.CharField(blank=True, default='', max_length=80)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='error', max_length=80)),
                ('receipt', models.CharField(blank=True, default='', max_length=80)),
                ('offer_id', models.CharField(blank=True, default='', max_length=240)),
                ('notes', models.CharField(blank=True, default='', max_length=254)),
                ('payment_capture', models.BooleanField(default=True)),
                ('order_created', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 10, 17, 47, 347005))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 10, 17, 47, 343343)),
        ),
        migrations.AddField(
            model_name='splitorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='splitorder',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
