# Generated by Django 2.1.8 on 2020-03-23 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0022_auto_20200311_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topicname', models.CharField(default='Untitled', max_length=120)),
                ('sub_topicamount', models.IntegerField()),
                ('sub_topicdescription', models.CharField(default='Untitled', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='splitamountledger',
            name='topic_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 8, 55, 24, 668704)),
        ),
        migrations.AlterField(
            model_name='splitorder',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 8, 55, 24, 672523)),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topic_topic', to='coresetup.Topic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
