# Generated by Django 2.1.8 on 2020-03-23 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0023_auto_20200323_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitamountledger',
            name='sub_topic_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topic_ledger', to='coresetup.SubTopic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 8, 58, 45, 449653)),
        ),
        migrations.AlterField(
            model_name='splitorder',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 8, 58, 45, 453547)),
        ),
    ]
