# Generated by Django 2.1.8 on 2020-05-11 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0024_auto_20200323_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 42, 5, 959276)),
        ),
        migrations.AlterField(
            model_name='splitorder',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 42, 5, 963713)),
        ),
    ]
