# Generated by Django 2.1.8 on 2020-05-21 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0025_auto_20200511_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitamountledger',
            name='splitted_descriptions',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 7, 38, 26, 975108)),
        ),
        migrations.AlterField(
            model_name='splitorder',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 7, 38, 26, 979578)),
        ),
    ]
