# Generated by Django 2.1.8 on 2020-06-02 14:28

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresetup', '0026_auto_20200521_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitamountledger',
            name='gains_me',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='splitamountledger',
            name='owe',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='splitamountledger',
            name='spent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 28, 35, 646944)),
        ),
        migrations.AlterField(
            model_name='splitorder',
            name='order_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 28, 35, 650419)),
        ),
    ]
